___

TEXT MINING - #5 TOPIC MODELLING
___

# Non-Negative Matric Factorization

Let's repeat thet opic modeling task from the previous lecture, but this time, we will use NMF instead of LDA.

## Data

We will be using articles scraped from NPR (National Public Radio), obtained from their website [www.npr.org](http://www.npr.org)

In [1]:
import pandas as pd

In [2]:
url ='https://raw.githubusercontent.com/nluninja/text-mining-dataviz-aa2526/refs/heads/main/06-Topic_Modeling/npr.csv'

In [3]:
npr = pd.read_csv(url)

In [4]:
npr.head()

,Article
0,"In the Washington of 2016, even when the polic..."
1,Donald Trump has used Twitter — his prefe...
2,Donald Trump is unabashedly praising Russian...
3,"Updated at 2:50 p. m. ET, Russian President Vl..."
4,"From photography, illustration and video, to d..."


Notice how we don't have the topic of the articles! Let's use LDA to attempt to figure out clusters of the articles.

## Preprocessing

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer

**`max_df`**` : float in range [0.0, 1.0] or int, default=1.0`<br>
When building the vocabulary ignore terms that have a document frequency strictly higher than the given threshold (corpus-specific stop words). If float, the parameter represents a proportion of documents, integer absolute counts. This parameter is ignored if vocabulary is not None.

**`min_df`**` : float in range [0.0, 1.0] or int, default=1`<br>
When building the vocabulary ignore terms that have a document frequency strictly lower than the given threshold. This value is also called cut-off in the literature. If float, the parameter represents a proportion of documents, integer absolute counts. This parameter is ignored if vocabulary is not None.

In [6]:
tfidf = TfidfVectorizer(max_df=0.95, min_df=0.2, stop_words='english')

In [7]:
dtm = tfidf.fit_transform(npr['Article'])

In [8]:
dtm

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 349867 stored elements and shape (11992, 96)>

## NMF

In [9]:
from sklearn.decomposition import NMF

In [10]:
nmf_model = NMF(n_components=7,random_state=42)

In [11]:
# This can take awhile, we're dealing with a large amount of documents!
nmf_model.fit(dtm)

NMF(n_components=7, random_state=42)

## Displaying Topics

In [12]:
len(tfidf.get_feature_names_out())

96

In [13]:
len(nmf_model.components_)

7

In [14]:
nmf_model.components_

array([[1.87365177e-01, 2.34088345e-01, 1.11858211e+00, 2.14565609e-02,
        1.77738970e-01, 3.60507622e-01, 2.64058317e-01, 0.00000000e+00,
        0.00000000e+00, 6.94057344e-01, 4.31509020e-01, 7.61246480e-01,
        8.60765599e-02, 1.44765171e-01, 8.32125975e-04, 4.73808012e-01,
        4.70527770e-01, 4.47995272e-01, 8.26684595e-01, 4.32546609e-01,
        0.00000000e+00, 6.86485099e-02, 6.73958315e-02, 8.40737212e-02,
        1.57216595e-01, 2.90191351e-01, 4.17300268e-02, 5.20461912e-01,
        1.27375736e-01, 3.06633355e-01, 1.78086813e-02, 2.17405377e-01,
        9.23761258e-01, 5.04820125e-01, 2.32958574e-01, 2.45851038e-01,
        9.74300309e-01, 5.71093563e-01, 2.61682668e-01, 0.00000000e+00,
        1.58986327e-01, 5.93725701e-01, 5.94462312e-02, 0.00000000e+00,
        9.72407628e-04, 9.57840959e-02, 1.83904828e-01, 1.93416646e-02,
        0.00000000e+00, 9.34771311e-02, 6.65079621e-02, 5.64941074e-01,
        1.78551443e-01, 0.00000000e+00, 1.17159104e+00, 1.169736

In [15]:
len(nmf_model.components_[0])

96

In [16]:
single_topic = nmf_model.components_[0]

In [17]:
# Returns the indices that would sort this array.
single_topic.argsort()

array([ 7,  8, 20, 57, 63, 53, 43, 39, 58, 48, 74, 73, 72, 68, 70, 69, 80,
       93, 87, 14, 44, 82, 30, 47, 85,  3, 94, 26, 42, 50, 22, 21, 56, 23,
       12, 49, 45, 28, 13, 71, 24, 40, 81,  4, 52, 64, 60, 46,  0, 31, 83,
       91, 34,  1, 59, 86, 35, 38,  6, 92, 77, 25, 29, 95,  5, 10, 19, 84,
       76, 17, 89, 16, 15, 90, 33, 27, 79, 88, 51, 75, 37, 41, 62, 67,  9,
       66, 11, 18, 32, 36,  2, 55, 54, 61, 78, 65])

In [18]:
# Word least representative of this topic
single_topic[48]

np.float64(0.0)

In [19]:
# Word most representative of this topic
single_topic[65]

np.float64(9.658524138794395)

In [20]:
# Top 10 words for this topic:
single_topic.argsort()[-10:]

array([11, 18, 32, 36,  2, 55, 54, 61, 78, 65])

In [21]:
top_word_indices = single_topic.argsort()[-10:]

In [22]:
for index in top_word_indices:
    print(tfidf.get_feature_names_out()[index])

case
did
government
house
according
npr
news
president
told
said


These look like business articles perhaps... Let's confirm by using .transform() on our vectorized articles to attach a label number. But first, let's view all the 10 topics found.

In [23]:
for index,topic in enumerate(nmf_model.components_):
    print(f'THE TOP 15 WORDS FOR TOPIC #{index}')
    print([tfidf.get_feature_names_out()[i] for i in topic.argsort()[-15:]])
    print('\n')

THE TOP 15 WORDS FOR TOPIC #0
['later', 'public', 'saying', 'called', 'say', 'case', 'did', 'government', 'house', 'according', 'npr', 'news', 'president', 'told', 'said']


THE TOP 15 WORDS FOR TOPIC #1
['change', 'news', 'think', 'saying', 'new', 'country', 'american', 'going', 'national', 'week', 'states', 'white', 'house', 'president', 'trump']


THE TOP 15 WORDS FOR TOPIC #2
['lot', 'group', 'work', 'ago', 'need', 'don', 'say', 'use', 'used', 'like', 'years', 'just', 'help', 'university', 'says']


THE TOP 15 WORDS FOR TOPIC #3
['make', 'kind', 'story', 'world', 'things', 'don', 've', 'really', 'way', 'time', 'life', 'think', 'know', 'just', 'like']


THE TOP 15 WORDS FOR TOPIC #4
['including', '10', 'public', 'npr', 'american', 'national', 'country', 'government', 'years', 'world', '000', 'according', 'year', 'new', 'percent']


THE TOP 15 WORDS FOR TOPIC #5
['need', 'public', 've', 'use', 'group', '000', 'want', 'going', 'lot', 'help', 'say', 'think', 'country', 'don', 'people']

### Attaching Discovered Topic Labels to Original Articles

In [24]:
dtm

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 349867 stored elements and shape (11992, 96)>

In [25]:
dtm.shape

(11992, 96)

In [26]:
len(npr)

11992

In [27]:
topic_results = nmf_model.transform(dtm)

In [28]:
topic_results.shape

(11992, 7)

In [29]:
topic_results[0]

array([0.0114954 , 0.15079102, 0.00062884, 0.02150612, 0.02212527,
       0.        , 0.        ])

In [30]:
topic_results[0].round(2)

array([0.01, 0.15, 0.  , 0.02, 0.02, 0.  , 0.  ])

In [31]:
topic_results[0].argmax()

np.int64(1)

This means that our model thinks that the first article belongs to topic #1.

### Combining with Original Data

In [32]:
npr.head()

,Article
0,"In the Washington of 2016, even when the polic..."
1,Donald Trump has used Twitter — his prefe...
2,Donald Trump is unabashedly praising Russian...
3,"Updated at 2:50 p. m. ET, Russian President Vl..."
4,"From photography, illustration and video, to d..."


In [33]:
topic_results.argmax(axis=1)

array([1, 1, 1, ..., 4, 1, 5])

In [34]:
npr['Topic'] = topic_results.argmax(axis=1)

In [35]:
npr.head(10)

,Article,Topic
0,"In the Washington of 2016, even when the polic...",1
1,Donald Trump has used Twitter — his prefe...,1
2,Donald Trump is unabashedly praising Russian...,1
3,"Updated at 2:50 p. m. ET, Russian President Vl...",1
4,"From photography, illustration and video, to d...",4
5,I did not want to join yoga class. I hated tho...,3
6,With a who has publicly supported the debunk...,4
7,"I was standing by the airport exit, debating w...",2
8,"If movies were trying to be more realistic, pe...",2
9,"Eighteen years ago, on New Year’s Eve, David F...",3


## Great work!